<a href="https://colab.research.google.com/github/johntremolo/EmKa-Veri-Bilimi-Kutuphaneleri/blob/main/EmKaOdev1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [132]:
#1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene Atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin
import numpy as np
import pandas as pd

array3d = np.array([[[1, 2, 3]], [[10, 20, 30]], [[100, 200, 300]]])
array3d.ndim

3

In [133]:
#2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.
array = np.arange(34,113,6)
array

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [134]:
#3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)
arrlin = np.linspace(50,500,91, dtype=int)
print(arrlin)
len(arrlin)

[ 50  55  60  65  70  75  80  85  90  95 100 105 110 115 120 125 130 135
 140 145 150 155 160 165 170 175 180 185 190 195 200 205 210 215 220 225
 230 235 240 245 250 255 260 265 270 275 280 285 290 295 300 305 310 315
 320 325 330 335 340 345 350 355 360 365 370 375 380 385 390 395 400 405
 410 415 420 425 430 435 440 445 450 455 460 465 470 475 480 485 490 495
 500]


91

In [135]:
#4) 100(10**2) ile 10000(10**5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.
arrlog = np.logspace(2,5,8)
arrlog

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

In [136]:
#5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.
arr3x3 = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [137]:
#6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)
zero = np.zeros((6,6),dtype=int)
zero

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [138]:
#7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)
one = np.ones((4,4),dtype=int)
one 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [139]:
#8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)
birim = np.eye(8,dtype=int)
birim

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [140]:
#9) 5x5 formatında bir köşegen matrisi oluşturun 
#(Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)
kosegen = np.eye(5, dtype=int)
kosegen3 = 3*kosegen
kosegen3

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [141]:
#10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.
rand = np.random.rand(6)
rand

array([0.47497101, 0.28849997, 0.27404831, 0.16076645, 0.93308802,
       0.49418438])

In [142]:
#11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.
rand2 = np.random.randint(50,101,(5,2))
print(rand2)
rand2.shape

[[69 67]
 [79 64]
 [71 59]
 [71 91]
 [66 51]]


(5, 2)

In [143]:
#12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. 
#Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.
rand3 = np.random.randint(100,1000,(2,5,5),dtype=int)
print(rand3)
print(rand3.ndim)
rand3.shape


[[[927 264 806 761 190]
  [662 565 548 866 354]
  [318 250 873 447 445]
  [494 247 970 831 152]
  [903 264 180 150 530]]

 [[547 854 579 460 353]
  [168 899 758 940 271]
  [820 417 149 494 222]
  [307 934 193 785 361]
  [742 127 275 561 230]]]
3


(2, 5, 5)

In [144]:
#13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.
rand4 = np.random.randint(0,101,10,dtype=int)
print(rand4)
print(rand4.max())
print(rand4.argmax())
print(rand4.min())
print(rand4.argmin())

[51 83 26 45  2 63 25 24 92 24]
92
8
2
4


In [145]:
#14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. 
#Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın. ------->  (Sorunun bu kısmını anlamadım)
rand5 = np.random.randint(300,501,(2,2,5))
print(rand5)
print(rand5[1,1,1])
print(rand5[0,0,0])

[[[348 442 440 383 466]
  [411 495 456 430 392]]

 [[358 419 386 464 377]
  [363 373 303 308 414]]]
373
348


In [146]:
#15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. 
#Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.
arr = np.arange(51)
arr[20:36] = 500
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])